-- schema.sql — defines all tables for ProdiFy

-- Stores employee login credentials and basic info
CREATE TABLE IF NOT EXISTS employees (
    id VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'employee',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stores every processed screenshot result
CREATE TABLE IF NOT EXISTS submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    extracted_text TEXT,
    app_detected VARCHAR(100),
    activity_class VARCHAR(50),
    progress_score FLOAT DEFAULT 0,
    productivity_score FLOAT DEFAULT 0,
    image_path VARCHAR(255),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Stores alerts generated by the alert engine
CREATE TABLE IF NOT EXISTS alerts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id VARCHAR(20) NOT NULL,
    alert_type VARCHAR(50) NOT NULL,
    message VARCHAR(255),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Seed two test employees (password: 'test1234')
INSERT IGNORE INTO employees (id, name, password_hash, role) VALUES
('EMP001', 'Alice Johnson', SHA2('test1234', 256), 'employee'),
('EMP002', 'Bob Smith',    SHA2('test1234', 256), 'employee'),
('EMP003', 'Carol Davis', SHA2('test1234', 256), 'employee'),
('EMP004', 'David Lee',   SHA2('test1234', 256), 'employee'),
('EMP005', 'Eva Martin',  SHA2('test1234', 256), 'employee');
