# train_model.py — builds labeled dataset (500+ samples), trains TF-IDF + ML model, saves model.pkl

import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# ─── TRAINING DATA ────────────────────────────────────────────────────────────

data = [
    # ── PRODUCTIVE: Python coding ──
    ("def function return class import module package pip install", "Productive"),
    ("python script variables loops conditionals while for range", "Productive"),
    ("list dictionary tuple set append remove pop update keys values", "Productive"),
    ("lambda map filter reduce zip enumerate sorted reversed", "Productive"),
    ("try except finally raise exception error handling traceback", "Productive"),
    ("open read write file csv json pickle load dump with as", "Productive"),
    ("os path sys argv glob shutil mkdir rename delete exists", "Productive"),
    ("requests get post headers params response status code json", "Productive"),
    ("flask route app run debug host port endpoint return jsonify", "Productive"),
    ("django model view template url admin migrate makemigrations", "Productive"),
    ("pandas dataframe read csv merge groupby apply sort values", "Productive"),
    ("numpy array reshape dot transpose mean std axis linspace", "Productive"),
    ("matplotlib pyplot plot show xlabel ylabel title legend figure", "Productive"),
    ("sklearn model fit predict accuracy score train test split", "Productive"),
    ("tensorflow keras sequential dense compile fit evaluate predict", "Productive"),
    ("pytorch tensor autograd backward optimizer loss forward", "Productive"),
    ("asyncio await async def event loop gather run coroutine", "Productive"),
    ("unittest assert test case setup teardown mock patch", "Productive"),
    ("pip install requirements freeze virtualenv activate deactivate", "Productive"),
    ("class inheritance polymorphism encapsulation abstraction object", "Productive"),
    ("decorator property staticmethod classmethod self super init", "Productive"),
    ("regex pattern match search replace findall compile group", "Productive"),
    ("multiprocessing threading pool worker process queue lock", "Productive"),
    ("socket server client connect bind listen accept send recv", "Productive"),
    ("hashlib sha256 base64 encrypt decrypt token secret key", "Productive"),

    # ── PRODUCTIVE: JavaScript / Web ──
    ("function const let var async await fetch API endpoint", "Productive"),
    ("React component useState useEffect props render JSX export", "Productive"),
    ("Redux store dispatch action reducer middleware thunk saga", "Productive"),
    ("HTML div span class id href src alt input button form", "Productive"),
    ("CSS flex grid margin padding border radius shadow color font", "Productive"),
    ("JavaScript DOM querySelector addEventListener innerHTML style", "Productive"),
    ("Node.js express router middleware require module exports", "Productive"),
    ("npm install package.json scripts start build test lint", "Productive"),
    ("TypeScript interface type generic enum readonly optional", "Productive"),
    ("Vue.js component props emit watch computed template script", "Productive"),
    ("Angular service module directive component decorator inject", "Productive"),
    ("Next.js getServerSideProps getStaticProps page router link", "Productive"),
    ("Tailwind utility class responsive dark hover focus active", "Productive"),
    ("webpack babel config entry output loader plugin resolve", "Productive"),
    ("axios promise then catch error response interceptor headers", "Productive"),
    ("REST API GET POST PUT DELETE PATCH status code JSON body", "Productive"),
    ("GraphQL query mutation schema resolver type field argument", "Productive"),
    ("WebSocket real time connection message event emit broadcast", "Productive"),
    ("localStorage sessionStorage cookie token auth JWT bearer", "Productive"),
    ("CORS origin headers preflight request response middleware", "Productive"),

    # ── PRODUCTIVE: Database ──
    ("SELECT FROM WHERE GROUP BY ORDER BY HAVING LIMIT OFFSET", "Productive"),
    ("JOIN INNER LEFT RIGHT FULL OUTER ON USING NATURAL JOIN", "Productive"),
    ("INSERT INTO VALUES UPDATE SET DELETE FROM WHERE table", "Productive"),
    ("CREATE TABLE ALTER DROP INDEX PRIMARY KEY FOREIGN KEY", "Productive"),
    ("MySQL PostgreSQL SQLite database schema migration query", "Productive"),
    ("MongoDB collection document find insert update delete index", "Productive"),
    ("Redis cache key value expire TTL set get hset hget", "Productive"),
    ("ORM model query filter exclude annotate aggregate count", "Productive"),
    ("transaction commit rollback savepoint isolation level lock", "Productive"),
    ("normalization denormalization schema design ER diagram", "Productive"),

    # ── PRODUCTIVE: Git / DevOps ──
    ("git commit push pull merge branch rebase clone repository", "Productive"),
    ("git status diff log stash checkout reset hard soft HEAD", "Productive"),
    ("pull request code review approve merge conflict resolve", "Productive"),
    ("GitHub GitLab Bitbucket issue milestone label assignee", "Productive"),
    ("Docker container image build run pull push Dockerfile", "Productive"),
    ("docker-compose service volume network up down restart", "Productive"),
    ("Kubernetes pod deployment service ingress namespace kubectl", "Productive"),
    ("CI CD pipeline workflow action trigger build test deploy", "Productive"),
    ("AWS EC2 S3 Lambda RDS CloudWatch IAM role policy bucket", "Productive"),
    ("nginx apache reverse proxy load balancer SSL certificate", "Productive"),
    ("Linux bash shell script chmod chown sudo apt grep sed awk", "Productive"),
    ("SSH key pair connect server terminal command line remote", "Productive"),
    ("environment variable dotenv config secret production staging", "Productive"),
    ("monitoring logging alert metric dashboard Grafana Prometheus", "Productive"),
    ("Terraform Ansible infrastructure code provision deploy", "Productive"),

    # ── PRODUCTIVE: Documents and Office ──
    ("Dear team please find attached quarterly report agenda", "Productive"),
    ("invoice payment due client proposal budget estimate plan", "Productive"),
    ("presentation slides objectives deliverables timeline milestones", "Productive"),
    ("spreadsheet column row formula SUM AVERAGE VLOOKUP pivot", "Productive"),
    ("meeting minutes action items follow up deadline assigned", "Productive"),
    ("project proposal scope requirements stakeholders approval", "Productive"),
    ("contract terms conditions clause agreement sign date", "Productive"),
    ("annual report revenue expenses profit loss balance sheet", "Productive"),
    ("research paper abstract introduction methodology results", "Productive"),
    ("thesis dissertation literature review hypothesis conclusion", "Productive"),
    ("case study analysis findings recommendation implementation", "Productive"),
    ("business plan market analysis target audience strategy", "Productive"),
    ("user manual documentation guide steps procedure reference", "Productive"),
    ("technical specification API docs endpoint parameters", "Productive"),
    ("HR policy onboarding training performance review appraisal", "Productive"),
    ("legal document compliance regulatory audit checklist", "Productive"),
    ("marketing copy campaign audience reach conversion funnel", "Productive"),
    ("financial model forecast projection assumption scenario", "Productive"),
    ("data analysis visualization insight trend pattern chart", "Productive"),
    ("curriculum lesson plan assignment submission grading rubric", "Productive"),

    # ── PRODUCTIVE: Communication tools ──
    ("email subject reply forward attachment CC BCC inbox draft", "Productive"),
    ("Slack message channel thread reply mention workspace DM", "Productive"),
    ("Teams meeting chat message reply reaction status call", "Productive"),
    ("Zoom join meeting host participant screen share record", "Productive"),
    ("Gmail compose send receive label filter archive spam", "Productive"),
    ("Outlook calendar invite accept decline reschedule reminder", "Productive"),
    ("Jira ticket issue sprint backlog priority status done", "Productive"),
    ("Trello card board list checklist member label due date", "Productive"),
    ("Notion page block database table view filter property", "Productive"),
    ("Confluence page space macro comment version history", "Productive"),
    ("Asana task project timeline goal milestone dependency", "Productive"),
    ("Linear issue cycle roadmap project label priority estimate", "Productive"),
    ("Figma design frame component variant prototype share", "Productive"),
    ("Postman collection request environment variable test", "Productive"),
    ("VS Code editor terminal extension debug run settings", "Productive"),
    ("IntelliJ PyCharm WebStorm editor plugin run debug build", "Productive"),
    ("Chrome DevTools inspect network console source breakpoint", "Productive"),
    ("Jupyter notebook cell output kernel markdown run restart", "Productive"),
    ("Google Docs Sheets Drive comment suggestion version share", "Productive"),
    ("Tableau Power BI dashboard chart filter measure dimension", "Productive"),

    # ── PRODUCTIVE: Extra coding samples ──
    ("binary search tree node root leaf depth traversal inorder", "Productive"),
    ("linked list pointer next prev head tail insert delete", "Productive"),
    ("stack queue push pop enqueue dequeue LIFO FIFO implement", "Productive"),
    ("dynamic programming memoization tabulation subproblem optimal", "Productive"),
    ("sorting algorithm quicksort mergesort heapsort bubble insertion", "Productive"),
    ("time complexity space complexity big O notation analysis", "Productive"),
    ("recursion base case call stack depth factorial fibonacci", "Productive"),
    ("graph BFS DFS adjacency matrix list vertices edges path", "Productive"),
    ("hash table collision bucket chaining probing load factor", "Productive"),
    ("heap priority queue min max insert extract heapify", "Productive"),
    ("API versioning rate limiting pagination cursor offset", "Productive"),
    ("unit test integration test end to end test coverage mock", "Productive"),
    ("code review refactor clean code SOLID principles DRY", "Productive"),
    ("design pattern singleton factory observer strategy facade", "Productive"),
    ("microservices service mesh gateway discovery load balance", "Productive"),
    ("message queue RabbitMQ Kafka topic consumer producer event", "Productive"),
    ("cache invalidation TTL CDN edge server origin performance", "Productive"),
    ("OAuth2 JWT refresh token access token authorization code", "Productive"),
    ("HTTPS TLS certificate handshake encryption decryption", "Productive"),
    ("agile scrum sprint velocity story point retrospective", "Productive"),
    ("SQL injection XSS CSRF sanitize validate escape security", "Productive"),
    ("code documentation docstring comment inline block README", "Productive"),
    ("performance optimization profiler benchmark bottleneck", "Productive"),
    ("memory leak garbage collection reference counting heap", "Productive"),
    ("continuous integration deployment pipeline build artifact", "Productive"),

    # ── PRODUCTIVE: Data science ──
    ("machine learning supervised unsupervised classification regression", "Productive"),
    ("neural network hidden layer activation function backprop", "Productive"),
    ("feature engineering selection extraction normalization scale", "Productive"),
    ("cross validation k-fold stratified shuffle split evaluate", "Productive"),
    ("confusion matrix precision recall F1 score ROC AUC curve", "Productive"),
    ("random forest gradient boosting XGBoost LightGBM ensemble", "Productive"),
    ("natural language processing tokenize lemmatize stopword", "Productive"),
    ("computer vision image classification object detection CNN", "Productive"),
    ("clustering k-means DBSCAN hierarchical silhouette inertia", "Productive"),
    ("dimensionality reduction PCA t-SNE UMAP components", "Productive"),

    # ── NON-PRODUCTIVE: Social media ──
    ("Like Share Follow Trending Reels Stories Views Subscribe", "Non-productive"),
    ("Instagram Facebook Twitter TikTok YouTube Snapchat feed", "Non-productive"),
    ("viral meme trending hashtag influencer follower post story", "Non-productive"),
    ("tweet retweet notification explore discover for you page", "Non-productive"),
    ("watch video shorts clip reel entertainment funny comedy", "Non-productive"),
    ("profile bio avatar cover photo mutual friends suggestion", "Non-productive"),
    ("status update check in tag location photo album memories", "Non-productive"),
    ("live stream broadcast viewer comment heart reaction gift", "Non-productive"),
    ("Reddit upvote downvote subreddit post comment karma award", "Non-productive"),
    ("Discord server channel bot voice chat nitro emoji role", "Non-productive"),
    ("Quora answer question topic follower upvote space digest", "Non-productive"),
    ("LinkedIn connection request endorse skill recommendation", "Non-productive"),
    ("WhatsApp status group broadcast forward message delete", "Non-productive"),
    ("Telegram channel group bot sticker forward message pin", "Non-productive"),
    ("Pinterest pin board save discover idea aesthetic trend", "Non-productive"),
    ("Tumblr reblog aesthetic niche fandom fanart headcanon", "Non-productive"),
    ("BeReal front back camera notification add friend react", "Non-productive"),
    ("Threads reply repost quote mention follower following", "Non-productive"),
    ("share this post tag a friend comment below link in bio", "Non-productive"),
    ("double tap to like swipe up follow for more content", "Non-productive"),
    ("story highlight close friends archive saved collections", "Non-productive"),
    ("reel audio trending remix original sound duet stitch", "Non-productive"),
    ("notification bell all customized none pause mute", "Non-productive"),
    ("explore page suggested accounts similar content niche", "Non-productive"),
    ("caption hashtag location tag collab paid partnership", "Non-productive"),
("YouTube watch video subscribe like share views channel playlist", "Non-productive"),
("youtube.com watch video playing autoplay recommended sidebar", "Non-productive"),
("Subscribe 3K views weeks ago Starter Story channel video", "Non-productive"),
("Netflix YouTube Prime video watch episode season streaming play", "Non-productive"),

    # ── NON-PRODUCTIVE: Shopping ──
    ("Add to cart Wishlist Buy now 50% off Flash sale Discount", "Non-productive"),
    ("Amazon Flipkart Myntra Meesho product price rating review", "Non-productive"),
    ("offer deal cashback EMI checkout payment order shipment", "Non-productive"),
    ("fashion clothing shoes accessories electronics gadgets", "Non-productive"),
    ("compare price best deal limited stock free shipping return", "Non-productive"),
    ("coupon promo code apply discount save extra off today", "Non-productive"),
    ("Zomato Swiggy Blinkit Zepto order food deliver minutes", "Non-productive"),
    ("Nykaa beauty skincare makeup hair care personal care", "Non-productive"),
    ("AJIO Snapdeal Puma Nike Adidas brand sale collection", "Non-productive"),
    ("cart total subtotal tax shipping address delivery slot", "Non-productive"),
    ("product description specifications size chart color option", "Non-productive"),
    ("customer review rating star helpful verified purchase", "Non-productive"),
    ("pay now UPI card wallet net banking COD select payment", "Non-productive"),
    ("track order shipped out for delivery arrived expected", "Non-productive"),
    ("return exchange refund initiate pickup replacement policy", "Non-productive"),
    ("wish list save later notify me back in stock alert", "Non-productive"),
    ("clearance sale end of season festival Diwali offer big", "Non-productive"),
    ("recommended for you based on your browsing history", "Non-productive"),
    ("buy 1 get 1 free combo pack bundle offer grab now", "Non-productive"),
    ("Paytm PhonePe GPay reward cashback points redeem", "Non-productive"),
    ("new arrival trending now bestseller top rated popular", "Non-productive"),
    ("size XS S M L XL XXL fit slim regular loose stretch", "Non-productive"),
    ("color black white red blue green yellow pink purple", "Non-productive"),
    ("brand store official authentic genuine original product", "Non-productive"),
    ("sold by fulfilled prime delivery guaranteed fast", "Non-productive"),

    # ── NON-PRODUCTIVE: News and entertainment ──
    ("Breaking news celebrity spotted viral watch now click", "Non-productive"),
    ("cricket IPL score match live update highlights wicket", "Non-productive"),
    ("movie trailer release date box office collection cast", "Non-productive"),
    ("Netflix Prime Hotstar OTT series episode season streaming", "Non-productive"),
    ("sports football basketball score goal player transfer", "Non-productive"),
    ("gossip rumor scandal controversy exposed leaked video", "Non-productive"),
    ("top 10 list best worst ranked countdown revealed", "Non-productive"),
    ("horoscope zodiac astrology prediction today weekly", "Non-productive"),
    ("recipe cooking tutorial ingredients steps method serve", "Non-productive"),
    ("travel vlog destination guide tips tricks itinerary", "Non-productive"),
    ("fitness workout gym exercise routine calories burn", "Non-productive"),
    ("relationship advice dating tips love quote couple goal", "Non-productive"),
    ("motivational quote success mindset hustle grind win", "Non-productive"),
    ("funny video fail compilation reaction challenge prank", "Non-productive"),
    ("news headline politics election vote party leader rally", "Non-productive"),
    ("stock market sensex nifty crash bull bear trade invest", "Non-productive"),
    ("crypto bitcoin ethereum NFT token price pump dump moon", "Non-productive"),
    ("celebrity interview award show red carpet outfit look", "Non-productive"),
    ("sports highlights goal replay slow motion commentary", "Non-productive"),
    ("web series review rating spoiler episode recap ending", "Non-productive"),
    ("click here read more see full story watch now play", "Non-productive"),
    ("subscribe newsletter daily digest morning brief update", "Non-productive"),
    ("opinion editorial column debate controversy hot take", "Non-productive"),
    ("weather forecast temperature rain wind humidity UV", "Non-productive"),
    ("live score commentary over ball wicket run partnership", "Non-productive"),

    # ── NON-PRODUCTIVE: Gaming ──
    ("level up score high score game over play again respawn", "Non-productive"),
    ("health mana shield inventory weapon armor quest mission", "Non-productive"),
    ("PUBG Free Fire Valorant BGMI COD multiplayer ranked", "Non-productive"),
    ("leaderboard rank kill death ratio win lose squad team", "Non-productive"),
    ("Steam Epic Games launcher library download install play", "Non-productive"),
    ("Minecraft build craft survive explore biome spawn chest", "Non-productive"),
    ("GTA mission character car money cheat code wanted star", "Non-productive"),
    ("FIFA ultimate team player card pack open coin trade", "Non-productive"),
    ("Roblox game avatar robux obby simulator adopt pet", "Non-productive"),
    ("Among Us imposter crewmate task vote eject sabotage", "Non-productive"),
    ("Fortnite battle royale build edit piece storm zone", "Non-productive"),
    ("chess opening gambit endgame checkmate blunder puzzle", "Non-productive"),
    ("ludo snakes ladders dice roll move token home base", "Non-productive"),
    ("mobile legend hero skill combo jungle tower push win", "Non-productive"),
    ("game pass Xbox PlayStation controller trophy achievement", "Non-productive"),
    ("save game load checkpoint auto save new game continue", "Non-productive"),
    ("skin bundle cosmetic emote dance spray voice line", "Non-productive"),
    ("crate opening lucky spin gacha pull legendary rare epic", "Non-productive"),
    ("custom room private match spectate replay highlight clip", "Non-productive"),
    ("guild clan alliance war donate request upgrade troop", "Non-productive"),

    # ── NON-PRODUCTIVE: Miscellaneous ──
    ("meme funny joke humor laugh lol rofl lmao hilarious", "Non-productive"),
    ("BuzzFeed quiz personality test which character are you", "Non-productive"),
    ("astrology birth chart rising moon sign compatibility", "Non-productive"),
    ("fan fiction fanfic ship otp fandom headcanon AU story", "Non-productive"),
    ("wallpaper aesthetic dark light minimal cute download", "Non-productive"),
    ("ringtone alarm sound effect notification download free", "Non-productive"),
    ("fortune cookie random quote generator lucky number", "Non-productive"),
    ("chatting texting DM conversation emoji sticker GIF", "Non-productive"),
    ("binge watch autoplay next episode continue watching", "Non-productive"),
    ("scroll feed refresh load more see older posts timeline", "Non-productive"),
    ("celebrity net worth age height boyfriend girlfriend", "Non-productive"),
    ("random facts did you know interesting trivia history", "Non-productive"),
    ("clickbait you won't believe what happened next OMG", "Non-productive"),
    ("online shopping haul unboxing first impression review", "Non-productive"),
    ("ASMR relaxing satisfying oddly calming sleep sounds", "Non-productive"),
    ("reaction video watching first time blind commentary", "Non-productive"),
    ("podcast episode listen subscribe Spotify Apple stream", "Non-productive"),
    ("daily vlog morning routine night routine lifestyle", "Non-productive"),
    ("rank tier list S A B C D worst best opinion debate", "Non-productive"),
    ("drama tea spill receipts exposed cancelled problematic", "Non-productive"),

    # ── IDLE ──
    ("", "Idle"),
    ("12:45 PM", "Idle"),
    ("Monday March 2026", "Idle"),
    ("screensaver desktop wallpaper", "Idle"),
    ("lock screen password PIN enter", "Idle"),
    ("Windows logo loading startup shutdown restart", "Idle"),
    ("battery charging percent connected wifi signal", "Idle"),
    ("taskbar clock notification tray volume brightness", "Idle"),
    ("sleep mode hibernate wake resume unlock", "Idle"),
    ("blank screen no activity detected timeout", "Idle"),
    ("desktop icons recycle bin my computer file folder", "Idle"),
    ("right click menu new folder rename delete properties", "Idle"),
    ("start menu search bar type open run", "Idle"),
    ("control panel settings display sound network", "Idle"),
    ("file explorer drive local disk documents pictures", "Idle"),
    ("nothing visible black screen idle no text", "Idle"),
    ("cursor blinking empty page no content", "Idle"),
    ("loading please wait spinner progress bar", "Idle"),
    ("system update installing restart required later", "Idle"),
    ("antivirus scan running complete no threats found", "Idle"),
    ("screensaver fish bubbles moving clock analog digital", "Idle"),
    ("wallpaper mountain sunset nature abstract minimal", "Idle"),
    ("notification popup toast message dismiss close", "Idle"),
    ("volume control mute unmute speaker headphone", "Idle"),
    ("wifi connected disconnected airplane mode bluetooth", "Idle"),
    ("away be right back brb status indicator presence", "Idle"),
    ("screen timeout lock activate dim power saver mode", "Idle"),
    ("no windows open empty desktop background only", "Idle"),
    ("mouse cursor moving no application foreground", "Idle"),
    ("system tray icons only time date display visible", "Idle"),
]

texts  = [d[0] for d in data]
labels = [d[1] for d in data]

print(f"Total training samples: {len(data)}")

# ─── TRAIN ────────────────────────────────────────────────────────────────────

X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1)),
    ("clf",   LogisticRegression(max_iter=1000, random_state=42))
])

pipeline.fit(X_train, y_train)

# ─── EVALUATE ─────────────────────────────────────────────────────────────────

y_pred = pipeline.predict(X_test)
print("\n--- Model Evaluation ---")
print(classification_report(y_test, y_pred))

# ─── SAVE ─────────────────────────────────────────────────────────────────────

with open("model.pkl", "wb") as f:
    pickle.dump(pipeline, f)

print("✅ model.pkl saved successfully.")
